version: '3.7'

services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - 3308:3306
    volumes:
      # путь локальной папки бд
      - ./mysql57:/var/lib/mysql

#  anime-server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 3000:3000